# ═══════════════════════════════════════════════════════════════════════════
# QUICK INDEX
# ═══════════════════════════════════════════════════════════════════════════
# 名称: Research Mechanism Agent / 研究机制智能体
# 版本: 1.1
#
# 一句话: 构建因果推理DAG，生成可证伪的投资论点
#
# 何时用:
#   - 当需要将定性判断转化为因果假设时
#   - 当需要做预验尸(Premortem)分析时
#   - 当需要识别生态系统风险(co-innovation/adoption chain)时
#
# 输入: 公司信息 + 初步研究发现 + 生态图谱
# 输出: ThesisMemo + Mechanism DAG + 监控触发器 + 不确定性矩阵
#
# 依赖: ecosystem_graph_agent, data_integrity_agent
# 被依赖: quality_gate_agent, valuation_engine_agent
#
# 状态: active
# ═══════════════════════════════════════════════════════════════════════════

# Research Mechanism Agent v1.1 (Merged & Optimized)
# 研究机制智能体 - 因果推理与论点构建
# 整合：Adner生态风险 + Pearl因果推断 + Klein预验尸 + OWASP LLM安全门禁

agent:
  name: research_mechanism_agent
  version: "1.1.0"
  purpose: |
    Compile a falsifiable, audit-ready ThesisMemo by building:
    - Mechanism DAG (cause-effect structure)
    - Counterfactual checks (do(x))
    - Adner ecosystem risk mapping (initiative/co-innovation/adoption chain)
    - Premortem failure modes + disconfirmers
    - Monitoring triggers + uncertainty matrix
    Enforce deterministic DEGRADE behavior when evidence/observability is weak.
  owner: "investment_super_agent"
  timezone: "America/Los_Angeles"

---

# 理论基础
theory_foundation:
  causality:
    - name: "Judea Pearl - Causality"
      application: "do(x)反事实推断、因果图"
      concepts: [do_operator, counterfactual_reasoning, causal_dag, identifiability]

  ecosystem_risk:
    - name: "Ron Adner - The Wide Lens"
      application: "生态系统风险分类"
      concepts: [initiative_risk, co_innovation_risk, adoption_chain_risk, ecosystem_carryover]

  red_teaming:
    - name: "Gary Klein - Premortem"
      application: "前瞻性失败分析"
      concepts: [prospective_hindsight, failure_mode_identification, disconfirmers]

  falsifiability:
    - name: "Karl Popper - Conjectures and Refutations"
      application: "可证伪性要求"
      concepts: [falsifiability_criterion, observable_predictions, theory_testing]

---

# 输入输出契约
contracts:
  input_refs:
    - name: run_id
      type: "string"
      required: true
      description: "本次运行UUID"

    - name: entity
      type: "Entity"
      required: true
      schema:
        ticker: string
        company_name: string
        cik: string (optional)

    - name: ecosystem_package_ref
      type: "EcosystemPackage"
      required: true
      from: "ecosystem_graph_agent"

    - name: data_confidence_ref
      type: "DataConfidenceReport"
      required: true
      from: "data_integrity_agent"

    - name: upstream_invariants
      type: "InvariantResults[]"
      required: true

    - name: upstream_confidence_cap
      type: "float"
      required: true
      range: [0.0, 1.0]

  outputs:
    - name: thesis_memo
      type: "ThesisMemo"
      schema: "schemas/rm_thesis_memo_schema.yaml"

    - name: monitoring_triggers
      type: "MonitoringTriggers[]"
      schema: "schemas/rm_trigger_schema.yaml"

    - name: rm_decision_trace_fragment
      type: "DecisionTrace"
      schema: "schemas/decision_trace_schema.yaml"

---

# Policy Pack配置
policy_pack:
  path: "policies/rm_policy_pack_v1.1.yaml"
  require_hash_freeze: true

---

# 执行配置
execution:
  max_retries: 2
  timeout_ms_total: 180000
  step_timeout_ms_default: 45000
  deterministic_rules:
    - "No investment conclusion in DEGRADE mode"
    - "LLM output cannot override deterministic gates"
    - "Confidence cap propagates: downstream <= min(upstream, internal)"
  parallelism:
    enabled: true
    max_concurrency: 3

---

# Blackboard（共享状态板）
blackboard:
  mode: "append_only"
  description: "所有状态变更为追加模式，保证可审计和可重放"
  required_keys:
    - run_id
    - policy_pack_version
    - policy_pack_hash
    - claim_registry
    - mechanism_dag
    - counterfactuals
    - ecosystem_risks
    - disconfirmers
    - evidence_registry
    - gate_history
    - reason_codes_all
  write_rules:
    - "Each step writes an append-only event with step_id, inputs_ref, outputs_ref, stats, reason_codes"
    - "Same run_id cannot change policy_pack_hash"
    - "Confidence can only decrease, never increase mid-run"

---

# Pipeline（6个核心Skills）
pipeline:
  # Step 0: Policy Pack加载器
  - step_id: "S0_policy_pack_loader"
    skill_ref: "skills_xml/rm_policy_pack_loader_v1.1.skill.xml"
    inputs:
      run_id: "{{inputs.run_id}}"
      policy_pack_path: "{{policy_pack.path}}"
    outputs_to_blackboard:
      - policy_ref
      - policy_pack_version
      - policy_pack_hash
    on_fail:
      action: "ABORT"
      reason_codes: ["RM_POLICY_LOAD_FAILED", "RM_POLICY_HASH_MISMATCH"]

  # Step 1: Claims提取 + DAG构建
  - step_id: "S1_claim_and_dag_builder"
    skill_ref: "skills_xml/rm_claim_and_dag_builder_v1.1.skill.xml"
    inputs:
      policy_ref: "{{blackboard.policy_ref}}"
      ecosystem_package_ref: "{{inputs.ecosystem_package_ref}}"
      data_confidence_ref: "{{inputs.data_confidence_ref}}"
      upstream_confidence_cap: "{{inputs.upstream_confidence_cap}}"
      upstream_invariants: "{{inputs.upstream_invariants}}"
    outputs_to_blackboard:
      - claim_registry
      - mechanism_dag
      - rm_internal_confidence
      - rm_confidence_cap

  # Step 2: 反事实编译
  - step_id: "S2_counterfactual_compiler"
    skill_ref: "skills_xml/rm_counterfactual_compiler_v1.1.skill.xml"
    inputs:
      policy_ref: "{{blackboard.policy_ref}}"
      claim_registry: "{{blackboard.claim_registry}}"
      rm_confidence_cap: "{{blackboard.rm_confidence_cap}}"
    outputs_to_blackboard:
      - counterfactuals

  # Step 3: Adner风险映射
  - step_id: "S3_adner_risk_mapper"
    skill_ref: "skills_xml/rm_adner_risk_mapper_v1.1.skill.xml"
    inputs:
      policy_ref: "{{blackboard.policy_ref}}"
      ecosystem_package_ref: "{{inputs.ecosystem_package_ref}}"
      claim_registry: "{{blackboard.claim_registry}}"
      rm_confidence_cap: "{{blackboard.rm_confidence_cap}}"
    outputs_to_blackboard:
      - ecosystem_risks

  # Step 4: Premortem + Disconfirmers
  - step_id: "S4_premortem_disconfirmers"
    skill_ref: "skills_xml/rm_premortem_disconfirmers_v1.1.skill.xml"
    inputs:
      policy_ref: "{{blackboard.policy_ref}}"
      claim_registry: "{{blackboard.claim_registry}}"
      counterfactuals_ref: "{{blackboard.counterfactuals}}"
      ecosystem_risks_ref: "{{blackboard.ecosystem_risks}}"
    outputs_to_blackboard:
      - failure_modes
      - disconfirmers

  # Step 5: Triggers + ThesisMemo组装
  - step_id: "S5_trigger_and_memo_assembler"
    skill_ref: "skills_xml/rm_trigger_and_memo_assembler_v1.1.skill.xml"
    inputs:
      policy_ref: "{{blackboard.policy_ref}}"
      claim_registry: "{{blackboard.claim_registry}}"
      mechanism_dag_ref: "{{blackboard.mechanism_dag}}"
      counterfactuals_ref: "{{blackboard.counterfactuals}}"
      ecosystem_risks_ref: "{{blackboard.ecosystem_risks}}"
      disconfirmers_ref: "{{blackboard.disconfirmers}}"
      upstream_confidence_cap: "{{inputs.upstream_confidence_cap}}"
      rm_internal_confidence: "{{blackboard.rm_internal_confidence}}"
    outputs_to_blackboard:
      - thesis_memo
      - monitoring_triggers
      - degrade_mode
      - reason_codes_all
    on_output:
      if: "{{output.degrade_mode}} == true"
      then:
        tag_output: ["DEGRADE_NO_INVESTMENT_CONCLUSION"]

---

# 分析引擎层Skills（现有，被S1消费）
analysis_engines:
  description: "这些skills的输出被S1_claim_and_dag_builder消费"
  skills:
    - id: competitive_analysis_framework_v1_3
      file: "competitive_analysis_framework_v1.3.skill.md"
      outputs: ["competition_surface", "ews_dashboard", "evidence_list"]

    - id: competitive_advantage_models_v1_2
      file: "competitive_advantage_models_quickref_v1.2.skill.md"
      outputs: ["models_hit", "leading_signals", "falsifiers"]

    - id: moat_evaluation_framework_v1_3
      file: "moat_evaluation_framework_v1.3.skill.md"
      outputs: ["moat_score", "strength_rating", "erosion_risks"]

    - id: first_principles_analysis_v1_2
      file: "first_principles_analysis_protocol_v1.2.skill.md"
      outputs: ["dominant_terms", "constraints", "scenario_paths"]

    - id: controller_spec_analysis_v4_2
      file: "controller_spec_analysis_framework_v4.2.skill.md"
      outputs: ["observability_matrix", "safety_controller", "voi_assessment"]

    - id: macro_industry_cycle_v1_3
      file: "macro_industry_cycle_analysis_v1.3.skill.md"
      outputs: ["cycle_phase", "confidence", "triggers"]

    - id: systemic_foresight_strategic_v1_2
      file: "systemic_foresight_strategic_analysis_v1.2.skill.md"
      outputs: ["flywheel_map", "options_tree", "dependency_kill_list"]

    - id: brand_experience_analysis_v1_0
      file: "brand_experience_analysis_v1.0.skill.md"
      outputs: ["brandexp_score", "mental_availability", "dba_register"]

---

# 下游集成
integration:
  downstream_handoff:
    to_quality_gate:
      payload:
        rm_confidence_cap: "{{blackboard.rm_confidence_cap}}"
        degrade_mode: "{{blackboard.degrade_mode}}"
        rm_reason_codes: "{{blackboard.reason_codes_all}}"
        thesis_memo: "{{blackboard.thesis_memo}}"
        monitoring_triggers: "{{blackboard.monitoring_triggers}}"
        invariants_results: "{{blackboard.invariants_results}}"
      contract: "contracts/rm_qg_interface_contract.yaml"

    to_eval_agent:
      payload:
        thesis_memo: "{{blackboard.thesis_memo}}"
        mechanism_dag: "{{blackboard.mechanism_dag}}"
        claims: "{{blackboard.claim_registry}}"
        decision_trace: "{{blackboard.decision_trace_fragment}}"
      test_types:
        - golden_outcome: "论点结构快照"
        - metamorphic: "证据单调性、噪声鲁棒性"
        - governance: "不变量必须pass"
        - regression: "claims完整性不降级"

  # Reason Code路由矩阵
  routing_matrix:
    - match_reason_codes: ["RM_EVIDENCE_GAP_CRITICAL", "RM_CLAIM_MISSING_OBSERVABLE"]
      route_to: "data_integrity_agent"
      action: "fetch_additional_sources"
      max_retries: 1
      description: "证据不足时请求DI补充"

    - match_reason_codes: ["RM_ECOSYSTEM_RISK_UNMAPPED", "RM_ADOPTION_CHAIN_UNSPECIFIED"]
      route_to: "ecosystem_graph_agent"
      action: "expand_dependency_edges"
      max_retries: 1
      description: "生态风险未映射时请求ECO扩展"

    - match_reason_codes: ["RM_POLICY_HASH_MISMATCH", "RM_POLICY_LOAD_FAILED"]
      route_to: "supervisor"
      action: "abort_run_and_report"
      max_retries: 0
      description: "策略包错误时终止运行"

    - match_reason_codes: ["RM_FALSIFIABILITY_MISSING", "RM_PREMORTEM_NOT_LINKED_TO_CLAIMS"]
      route_to: "self"
      action: "rerun_with_stricter_validation"
      max_retries: 1
      description: "可证伪性问题时自我重试"

---

# Artifacts（工件输出）
artifacts:
  root: "artifacts/runs/{{run_id}}/rm/"
  files:
    - name: "thesis_memo.json"
      from: "{{blackboard.thesis_memo}}"
      schema: "schemas/rm_thesis_memo_schema.yaml"

    - name: "monitoring_triggers.json"
      from: "{{blackboard.monitoring_triggers}}"
      schema: "schemas/rm_trigger_schema.yaml"

    - name: "mechanism_dag.json"
      from: "{{blackboard.mechanism_dag}}"
      schema: "schemas/rm_mechanism_dag_schema.yaml"

    - name: "claim_registry.json"
      from: "{{blackboard.claim_registry}}"
      schema: "schemas/rm_claim_spec_schema.yaml"

    - name: "rm_decision_trace_fragment.json"
      from: "{{blackboard.decision_trace_fragment}}"
      schema: "schemas/decision_trace_schema.yaml"

---

# 配置文件清单
config_files:
  P0_required:
    - file: "policies/rm_policy_pack_v1.1.yaml"
      purpose: "策略包（阈值、规则、配置）"

    - file: "reason_codes/reason_code_dictionary_RM.yaml"
      purpose: "RM命名空间reason codes"

    - file: "schemas/rm_claim_spec_schema.yaml"
      purpose: "Claim规范Schema"

    - file: "schemas/rm_mechanism_dag_schema.yaml"
      purpose: "机制DAG Schema"

    - file: "schemas/rm_trigger_schema.yaml"
      purpose: "监控触发器Schema"

    - file: "schemas/rm_thesis_memo_schema.yaml"
      purpose: "ThesisMemo Schema"

    - file: "schemas/decision_trace_schema.yaml"
      purpose: "决策追踪Schema"

  P1_recommended:
    - file: "contracts/rm_upstream_interface_contract.yaml"
      purpose: "上游接口契约"

    - file: "contracts/rm_qg_interface_contract.yaml"
      purpose: "QG接口契约"

    - file: "invariants/rm_invariants_manifest.yaml"
      purpose: "不变量清单（21个）"

  skills_xml:
    - file: "skills_xml/rm_policy_pack_loader_v1.1.skill.xml"
    - file: "skills_xml/rm_claim_and_dag_builder_v1.1.skill.xml"
    - file: "skills_xml/rm_counterfactual_compiler_v1.1.skill.xml"
    - file: "skills_xml/rm_adner_risk_mapper_v1.1.skill.xml"
    - file: "skills_xml/rm_premortem_disconfirmers_v1.1.skill.xml"
    - file: "skills_xml/rm_trigger_and_memo_assembler_v1.1.skill.xml"

---

# 版本历史
version_history:
  - version: "1.1.0"
    date: "2026-01-27"
    changes:
      - "合并优化：6个XML核心Skills（精简自9个YAML）"
      - "新增blackboard append-only模式"
      - "新增routing_matrix路由矩阵"
      - "新增artifacts工件输出配置"
      - "新增decision_trace_schema审计追踪"
      - "保留21个不变量 + 50+ reason codes"
      - "保留upstream/qg接口契约"
      - "整合Adner/Pearl/Klein理论框架"
      - "DEGRADE模式强制禁止投资建议"

  - version: "1.0"
    date: "2026-01-26"
    changes:
      - "初始8个分析引擎skills"
      - "基础竞争/护城河/周期分析"
