name: policy-scenario-analyzer
description: 政策情景分析器 - 专门分析环保政策、法规变化对生态科技公司的影响，建立政策敏感性和监管风险评估模型
version: "1.0"
author: "投资研究Agent v19.12"
category: policy_analysis

triggers:
  - "政策环境分析"
  - "监管风险评估"
  - "政策敏感性分析"
  - "法规影响评价"
  - "补贴政策研究"
  - "环保法规分析"

system_message: |
  你是政策情景分析专家，专门负责：
  1. 分析环保政策和法规对生态科技公司的影响
  2. 建立政策敏感性和风险评估模型
  3. 预测政策变化趋势和时间线
  4. 量化政策支持和监管风险的财务影响
  5. 设计政策对冲和适应策略

  核心专长：
  - 多国家/地区政策框架对比分析
  - 政策生命周期和执行时间线预测
  - 补贴政策和激励机制量化评估
  - 监管合规成本和风险量化
  - 政策套利机会识别和风险管理

analysis_framework:
  policy_landscape_mapping:
    global_frameworks:
      - paris_agreement: "巴黎协定减排承诺执行"
      - eu_green_deal: "欧盟绿色协议政策包"
      - us_ira: "美国通胀削减法案"
      - china_2060: "中国2060碳中和目标"
      - japan_green_growth: "日本绿色增长战略"

    regional_policies:
      - carbon_pricing: "碳定价机制(EU ETS, 碳税等)"
      - renewable_standards: "可再生能源配额标准"
      - emission_standards: "排放标准和限制"
      - green_building_codes: "绿色建筑规范"
      - esg_disclosure: "ESG信息披露要求"

  policy_impact_assessment:
    positive_drivers:
      subsidies_incentives: "补贴和激励政策量化"
      regulatory_support: "监管支持和优先政策"
      market_creation: "政策创造的市场机会"
      competitive_advantage: "政策带来的竞争优势"

    negative_pressures:
      compliance_costs: "合规成本和监管负担"
      policy_uncertainty: "政策不确定性风险"
      phase_out_risk: "政策退出和减少风险"
      international_trade: "贸易政策和关税影响"

policy_scenarios:
  scenario_1_supportive:
    description: "强力政策支持情景"
    assumptions:
      - "碳价格快速上升($100-200/tCO2e by 2030)"
      - "大规模绿色补贴延续和扩大"
      - "严格的环保法规全面执行"
      - "国际协调一致的政策框架"

    impact_modeling:
      revenue_impact: "+30-50% (政策驱动需求增长)"
      cost_impact: "+10-20% (合规和技术升级)"
      margin_impact: "+15-25% (净正面影响)"
      valuation_multiplier: "1.3-1.5x (政策确定性溢价)"

  scenario_2_moderate:
    description: "温和政策环境情景"
    assumptions:
      - "碳价格逐步上升($50-100/tCO2e by 2030)"
      - "选择性政策支持，重点行业"
      - "渐进式法规收紧"
      - "地区间政策差异化"

    impact_modeling:
      revenue_impact: "+15-30% (稳定增长)"
      cost_impact: "+5-15% (适度合规成本)"
      margin_impact: "+8-15% (温和正面影响)"
      valuation_multiplier: "1.1-1.3x (适度政策支持)"

  scenario_3_neutral:
    description: "政策中性情景"
    assumptions:
      - "碳价格缓慢上升($25-50/tCO2e by 2030)"
      - "现有政策维持，无重大新措施"
      - "最低限度法规要求"
      - "市场化机制为主导"

    impact_modeling:
      revenue_impact: "0-15% (市场驱动增长)"
      cost_impact: "0-10% (基础合规成本)"
      margin_impact: "0-5% (轻微正面或中性)"
      valuation_multiplier: "0.9-1.1x (无政策溢价)"

  scenario_4_restrictive:
    description: "政策收紧情景"
    assumptions:
      - "政策支持大幅减少或取消"
      - "新的监管限制和负担"
      - "保护主义贸易政策"
      - "化石燃料行业政策回摆"

    impact_modeling:
      revenue_impact: "-10-25% (政策阻力影响)"
      cost_impact: "+15-30% (高合规和适应成本)"
      margin_impact: "-20-40% (显著负面影响)"
      valuation_multiplier: "0.6-0.8x (政策风险折价)"

quantitative_modeling:
  policy_sensitivity_model:
    inputs:
      - policy_exposure_score: "政策敏感度评分(0-10)"
      - subsidy_dependence: "补贴依赖度(%收入)"
      - regulatory_compliance_cost: "合规成本($M/年)"
      - policy_timeline: "政策变化时间线(年)"
      - geographic_exposure: "地理政策风险敞口"

    calculation: |
      政策风险调整 = 基础估值 × (1 - 政策风险系数)
      政策风险系数 = (敏感度评分/10) × 政策不确定性系数 × 地理风险权重
      净政策价值 = 政策收益NPV - 政策成本NPV - 风险调整

  subsidy_impact_model:
    direct_subsidies:
      - production_tax_credits: "生产税收抵免"
      - investment_tax_credits: "投资税收抵免"
      - cash_grants: "直接现金补助"
      - loan_guarantees: "贷款担保优惠"

    indirect_benefits:
      - accelerated_depreciation: "加速折旧政策"
      - regulatory_fast_track: "监管绿色通道"
      - public_procurement: "政府采购优先"
      - r_d_funding: "研发资金支持"

    valuation_impact: |
      补贴价值 = Σ(年补贴金额 × 确定性系数 × 贴现因子)
      风险调整 = 补贴价值 × (1 - 政策风险概率)
      净补贴贡献 = 风险调整补贴价值 - 合规和申请成本

regional_analysis:
  us_market:
    key_policies:
      - ira_incentives: "IRA法案激励措施($370B绿色投资)"
      - state_rps: "州可再生能源配额标准"
      - cafe_standards: "汽车燃油经济性标准"
      - epa_regulations: "EPA环保法规"

    risk_factors:
      - political_volatility: "政治周期变化风险"
      - federal_vs_state: "联邦与州政策不一致"
      - sunset_clauses: "政策日落条款风险"
      - litigation_risk: "法律诉讼挑战风险"

  eu_market:
    key_policies:
      - green_deal: "欧盟绿色协议(€1T投资)"
      - fit55_package: "Fit for 55政策包"
      - eu_taxonomy: "欧盟可持续分类标准"
      - cbam: "碳边境调节机制"

    regulatory_advantages:
      - policy_certainty: "长期政策确定性"
      - harmonized_standards: "统一监管标准"
      - innovation_support: "创新研发支持"
      - market_integration: "统一大市场优势"

  china_market:
    key_policies:
      - carbon_neutrality_2060: "2060碳中和目标"
      - dual_control_system: "能源双控制度"
      - new_energy_vehicle_policy: "新能源汽车政策"
      - green_finance_standards: "绿色金融标准"

    execution_characteristics:
      - top_down_planning: "自上而下政策执行"
      - rapid_implementation: "政策执行速度快"
      - local_variation: "地方执行差异化"
      - industrial_policy: "产业政策导向明显"

sector_specific_analysis:
  renewable_energy:
    supportive_policies:
      - feed_in_tariffs: "上网电价补贴"
      - renewable_portfolio_standards: "可再生能源配额"
      - net_metering: "净计量政策"
      - green_certificates: "绿色证书交易"

    risk_factors:
      - grid_integration_requirements: "电网接入要求"
      - permitting_challenges: "许可审批挑战"
      - intermittency_penalties: "间歇性发电处罚"
      - fossil_fuel_subsidies: "化石燃料补贴竞争"

  electric_vehicles:
    supportive_policies:
      - purchase_incentives: "购买补贴和税收优惠"
      - ice_phase_out: "燃油车禁售时间表"
      - charging_infrastructure: "充电基础设施投资"
      - fleet_mandates: "政府车队采购要求"

    regulatory_requirements:
      - safety_standards: "安全标准认证"
      - battery_recycling: "电池回收要求"
      - data_privacy: "数据隐私保护"
      - autonomous_driving: "自动驾驶法规"

  carbon_capture:
    policy_drivers:
      - 45q_tax_credits: "45Q税收抵免(美国)"
      - innovation_funding: "创新研发资金"
      - industrial_decarbonization: "工业脱碳要求"
      - negative_emissions: "负排放技术支持"

    regulatory_frameworks:
      - ccs_permitting: "CCS项目许可框架"
      - liability_frameworks: "长期责任框架"
      - transport_regulations: "CO2运输监管"
      - storage_standards: "储存安全标准"

risk_assessment_framework:
  policy_risk_categories:
    regulatory_risk_high_7_10:
      - "依赖单一政策支持>50%收入"
      - "面临重大法规变化不确定性"
      - "政治敏感行业(如核能)"
      - "跨境监管复杂性高"

    regulatory_risk_medium_4_6:
      - "多元化政策支持组合"
      - "成熟监管框架环境"
      - "温和的政策依赖度"
      - "良好的政策适应历史"

    regulatory_risk_low_1_3:
      - "市场驱动增长模式"
      - "政策支持为锦上添花"
      - "强大的技术竞争力"
      - "多地区政策风险分散"

  timeline_analysis:
    short_term_0_2_years:
      - "现有政策执行和调整"
      - "政治选举周期影响"
      - "经济环境对政策影响"
      - "突发事件政策响应"

    medium_term_3_7_years:
      - "新政策框架建立"
      - "国际协议执行"
      - "技术标准制定"
      - "产业政策调整"

    long_term_8_15_years:
      - "结构性政策转型"
      - "国际治理框架演变"
      - "技术进步驱动政策变化"
      - "社会偏好长期转变"

monitoring_indicators:
  policy_development_tracking:
    legislative_pipeline:
      - "国会/议会法案进度"
      - "监管机构规则制定"
      - "国际协议谈判"
      - "行业标准制定进展"

    stakeholder_dynamics:
      - "行业游说活动强度"
      - "环保组织倡议影响"
      - "公众舆论变化"
      - "企业政策参与"

  early_warning_system:
    red_flags:
      - "主要政策支持者政治地位变化"
      - "经济衰退影响绿色政策优先级"
      - "国际贸易紧张关系加剧"
      - "技术竞争影响政策导向"

    opportunity_signals:
      - "新政府绿色承诺增强"
      - "极端天气事件推动政策紧迫性"
      - "技术成本下降减少政策依赖"
      - "国际合作框架加强"

output_deliverables:
  policy_scenario_report:
    executive_summary: "政策环境执行摘要"
    scenario_analysis: "4情景深度分析和概率权重"
    financial_impact: "各情景财务影响量化"
    risk_assessment: "政策风险综合评估"
    monitoring_framework: "政策跟踪监控体系"

  regulatory_compliance_assessment:
    current_requirements: "现有合规要求和成本"
    upcoming_changes: "即将到来的法规变化"
    compliance_roadmap: "合规路径和时间表"
    cost_benefit_analysis: "合规成本效益分析"

quality_standards:
  data_sources:
    tier_1_sources:
      - "政府官方政策文件"
      - "国际组织政策报告(OECD, IEA)"
      - "监管机构公开咨询"
      - "法律条文和实施细则"

    tier_2_sources:
      - "专业政策咨询机构"
      - "行业协会政策分析"
      - "学术研究机构报告"
      - "智库政策研究"

  confidence_calibration:
    high_confidence_8_10: "现行政策明确文件、历史执行记录"
    medium_confidence_6_8: "政策意向明确、实施细节待定"
    low_confidence_4_6: "政策方向性判断、具体措施不确定"

integration_protocols:
  with_environmental_impact: "环境效益与政策支持力度关联"
  with_carbon_economics: "政策碳价与市场碳价整合"
  with_technology_assessment: "政策对技术发展路径影响"
  with_financial_modeling: "政策敏感性财务模型输入"
  with_investment_strategy: "政策风险投资组合管理"

success_criteria:
  scenario_accuracy: "政策情景预测准确性 >70%"
  risk_identification: "政策风险识别完整性 >85%"
  quantification_reliability: "财务影响量化可靠性 >80%"
  monitoring_effectiveness: "政策监控体系有效性 >90%"
  strategic_value: "政策分析战略指导价值 >85%"